/* The Universal Animation Library's clips as an AI model picks them: tags, then one line on what the body does.
 * Written by hand from watching each clip (tools/anim-import.mjs converts the motion; this says what it is for).
 * "in place" clips keep the root still (the game moves the body); "root motion" clips travel by themselves. */
(window.MOCAP = window.MOCAP || {}).UAL_CATALOG = {
  A_TPose: ['reference', 'T-pose, arms straight out: the rest pose every clip is measured from'],
  Idle_Loop: ['idle', 'standing at rest, breathing and shifting weight'],
  Idle_Talking_Loop: ['idle talk', 'standing and talking with hand gestures'],
  Idle_Torch_Loop: ['idle prop', 'standing with one arm raised, holding up a torch or lantern'],
  Walk_Loop: ['walk', 'relaxed walk, in place'],
  Walk_Formal_Loop: ['walk', 'upright, measured walk, in place'],
  Jog_Fwd_Loop: ['run', 'jog, in place'],
  Sprint_Loop: ['run', 'full sprint with big arm swings, in place'],
  Crouch_Idle_Loop: ['crouch idle stealth', 'crouched low and still, looking about'],
  Crouch_Fwd_Loop: ['crouch walk stealth', 'crouched sneaking walk, in place'],
  Jump_Start: ['jump', 'dips, then springs up with the arms thrown out (in place: the game lifts the body)'],
  Jump_Loop: ['jump air', 'airborne pose held while rising or falling'],
  Jump_Land: ['jump', 'lands from a fall, knees soak it up, stands'],
  Roll: ['dodge', 'forward roll over the shoulder and back to standing, in place'],
  Roll_RM: ['dodge root-motion', 'forward roll that travels (root motion)'],
  Punch_Enter: ['unarmed stance', 'brings the fists up into a fighting stance'],
  Punch_Jab: ['unarmed attack', 'quick lead-hand jab from the stance'],
  Punch_Cross: ['unarmed attack', 'rear-hand straight punch with a hip turn'],
  Sword_Idle: ['sword idle', 'standing ready with a sword in the right hand'],
  Sword_Attack: ['sword attack', 'stepping one-handed slash, in place'],
  Sword_Attack_RM: ['sword attack root-motion', 'stepping one-handed slash that travels'],
  Spell_Simple_Enter: ['magic stance', 'raises a hand to ready a spell'],
  Spell_Simple_Idle_Loop: ['magic idle', 'holds a spell ready'],
  Spell_Simple_Shoot: ['magic attack', 'casts: drives the hand forward'],
  Spell_Simple_Exit: ['magic stance', 'lowers the casting hand'],
  Pistol_Idle_Loop: ['gun idle', 'standing ready, pistol held low in both hands'],
  Pistol_Aim_Neutral: ['gun aim pose', 'two-handed pistol aim, level (a pose to blend with up and down)'],
  Pistol_Aim_Up: ['gun aim pose', 'two-handed pistol aim, pointing up'],
  Pistol_Aim_Down: ['gun aim pose', 'two-handed pistol aim, pointing down'],
  Pistol_Shoot: ['gun attack', 'one pistol shot with recoil'],
  Pistol_Reload: ['gun', 'reloads the pistol'],
  Hit_Chest: ['hurt', 'takes a blow to the chest: torso snaps back, recovers'],
  Hit_Head: ['hurt', 'takes a blow to the head: head snaps aside, recovers'],
  Death01: ['death', 'staggers and falls flat on the back'],
  Interact: ['interact', 'reaches forward at chest height and works something with the hands (a lever, a door, a box)'],
  PickUp_Table: ['interact item', 'reaches out and picks something up from table height'],
  Push_Loop: ['interact push', 'leans in and shoves something heavy, stepping'],
  Fixing_Kneeling: ['work interact', 'kneels on one knee and works with both hands near the ground'],
  Sitting_Enter: ['sit', 'sits down onto a seat (no chair is drawn)'],
  Sitting_Idle_Loop: ['sit idle', 'seated at rest'],
  Sitting_Talking_Loop: ['sit talk', 'seated, talking with hand gestures'],
  Sitting_Exit: ['sit', 'stands up from a seat'],
  Driving_Loop: ['sit vehicle', 'seated, hands on a steering wheel, small turns'],
  Dance_Loop: ['emote dance', 'a one-second groove: hips sway, arms swing out'],
  Swim_Idle_Loop: ['swim idle', 'treading water, upright'],
  Swim_Fwd_Loop: ['swim', 'swimming forward, body flat'],
};
